url:        https://yld.me      # Base URL for all links
port:       9515                # Port to listen to
address:    127.0.0.1           # Bind address (to listen on)
max_tries:  10                  # Number of times to try to find an identifier

# alphabet:                     # Alphabet to use to form identifer
# assets:                       # Path to assets directory
# styles:                       # Path to styles directory
# uploads:                      # Path to uploads directory
# templates:                    # Path to templates directory

presets:
  - name:   url
    link:   https://yld.me
  - name:   paste
    link:   https://yld.me

  - name:   pbui
    link:   http://www3.nd.edu/~pbui

  - name:   cdt-30010-fa15
    link:   https://www3.nd.edu/~pbui/teaching/cdt.30010.fa15/

  - name:   cdt-30020-sp16
    link:   https://www3.nd.edu/~pbui/teaching/cdt.30020.sp16/
  - name:   cse-20189-sp16
    link:   https://www3.nd.edu/~pbui/teaching/cse.20189.sp16/
  - name:   cse-40175-sp16
    link:   https://www3.nd.edu/~pbui/teaching/cse.40175.sp16/

  - name:   cdt-30010-fa16
    link:   https://www3.nd.edu/~pbui/teaching/cdt.30010.fa16/
  - name:   cse-30331-fa16
    link:   https://www3.nd.edu/~pbui/teaching/cse.30331.fa16/
  - name:   cse-40175-fa16
    link:   https://www3.nd.edu/~pbui/teaching/cse.40175.fa16/

  - name:   cse-20289-sp17
    link:   https://www3.nd.edu/~pbui/teaching/cse.20289.sp17/
  - name:   cse-40175-sp17
    link:   https://www3.nd.edu/~pbui/teaching/cse.40175.sp17/
  - name:   cse-40842-sp17
    link:   https://www3.nd.edu/~pbui/teaching/cse.40842.sp17/

  - name:   pbc-su17
    link:   https://www3.nd.edu/~pbui/teaching/pbc.su17/

  - name:   cse-30341-fa17
    link:   https://www3.nd.edu/~pbui/teaching/cse.30341.fa17/
  - name:   cse-30872-fa17
    link:   https://www3.nd.edu/~pbui/teaching/cse.30872.fa17/
  - name:   cse-40175-fa17
    link:   https://www3.nd.edu/~pbui/teaching/cse.40175.fa17/

  - name:   cse-20289-sp18
    link:   https://www3.nd.edu/~pbui/teaching/cse.20289.sp18/
  - name:   cse-40175-sp18
    link:   https://www3.nd.edu/~pbui/teaching/cse.40175.sp18/
  - name:   cse-40850-sp18
    link:   https://www3.nd.edu/~pbui/teaching/cse.40850.sp18/

  - name:   eg-44175-su18
    link:   https://www3.nd.edu/~pbui/teaching/eg.44175.su18/

  - name:   cse-30341-fa18
    link:   https://www3.nd.edu/~pbui/teaching/cse.30341.fa18/
  - name:   cse-30872-fa18
    link:   https://www3.nd.edu/~pbui/teaching/cse.30872.fa18/
  - name:   cse-40175-fa18
    link:   https://www3.nd.edu/~pbui/teaching/cse.40175.fa18/

  - name:   cse-10001-sp19
    link:   https://www3.nd.edu/~pbui/teaching/cse.10001.sp19/
  - name:   cse-20289-sp19
    link:   https://www3.nd.edu/~pbui/teaching/cse.20289.sp19/
  - name:   cse-40842-sp19
    link:   https://www3.nd.edu/~pbui/teaching/cse.40842.sp19/

  - name:   cse-34872-su19
    link:   https://www3.nd.edu/~pbui/teaching/cse.34872.su19/
  - name:   pbc-su19
    link:   https://www3.nd.edu/~pbui/teaching/pbc.su19/
